# Site
title:              'Work Research Group'
bio:                'A transportation cyber physical systems lab at Vanderbilt University'
description:        "Our research group uses sensing technologies, models, data, and advanced analytics to understand mobility systems so that we can improve them. Our research projects explore the interplay between autonomous vehicles and phantom traffic jams. We also use large mobility datasets to understand urban traffic congestion at city scales, and freight rail traffic at the regional scale. We also build mathematical models and systems theory tools to understand the underlying behavior of traffic flow."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lab-work.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# update here to add a new site collection for indexing
collections:
  projects:
  research:
  teams:
  people:
  

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            dbwork
facebook:           default
instagram:          default
github:             Lab-Work

plugins:
  - jekyll-seo-tag

# personal
location:           Institute for Software Integrated Systems, 1025 16th Ave S, Suite 102, Nashville, TN 37212.
phone:              999-999-9999
email:              dan.work@vanderbilt.edu

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
